Explicitly don't add --recurse-submodules when --no-recurse-submodules is used

diff --git a/functions/git b/functions/git
--- a/functions/git
+++ b/functions/git
@@ -5,7 +5,7 @@
 # Author: Matthew Edwards
 
 _print_and_run () {
-  echo "$(tput dim)Correcting to $*$(tput sgr0)"
+  echo "$(tput dim)Running \"$*\" instead, use --no-recurse-submodules to prevent this.$(tput sgr0)"
   command "$@"
 }
 
@@ -30,16 +30,28 @@ git () {
     command git branch "$@"
   elif [[ "$1" == "clone" ]]; then
     shift 1
-    # After the clone is created, initialize and clone submodules.  This is
-    # equivalent to running `git submodule update --init --recursive` immediately
-    # after the clone is finished.
-    _print_and_run git clone --recurse-submodules "$@"
+    # shellcheck disable=SC2199
+    if [[ ${@[(ie)--no-recurse-submodules]} -gt ${#@} ]]; then
+      # Unless --no-recurse-submodules is provided, use --recurse-submodules:
+      # After the clone is created, initialize and clone submodules.  This is
+      # equivalent to running `git submodule update --init --recursive` immediately
+      # after the clone is finished.
+      _print_and_run git clone --recurse-submodules "$@"
+    else
+      command git clone "$@"
+    fi
   elif [[ "$1" == "checkout" || "$1" == "co" ]]; then
     shift 1
-    # Update the content of all initialized submodules according to the commit
-    # recorded in the superproject.  If local modifications in a submodule would
-    # be overwritten the checkout will fail unless -f is used.
-    _print_and_run git checkout --recurse-submodules "$@" || return $?
+    # shellcheck disable=SC2199
+    if [[ ${@[(ie)--no-recurse-submodules]} -gt ${#@} ]]; then
+      # Unless --no-recurse-submodules is provided, use --recurse-submodules:
+      # Update the content of all initialized submodules according to the commit
+      # recorded in the superproject.  If local modifications in a submodule would
+      # be overwritten the checkout will fail unless -f is used.
+      _print_and_run git checkout --recurse-submodules "$@" || return $?
+    else
+      command git checkout "$@" || return $?
+    fi
     _check_for_stashes
   elif [[ "$1" == "stash" && "$2" == "list" ]]; then
     shift 2
